package com.dodles.gdx.dodleengine.events;

/**
 * Defines the available types of events.
 */
public enum EngineEventType {
    ANIMATION_TOOL_BLOCK_CHANGED,
    ANIMATION_TIMELINE_POSITION_MOVED_BY_USER,
    CHANGE_EDITOR_STATE,
    DISPLAY_TRANSFORM_OVERLAY,
    ENGINE_CONFIG_CHANGED,
    ENGINE_POST_DRAW,
    ENGINE_PRE_DRAW,
    KEY_PRESS,
    PEEL_STACK_CHANGED,
    PHASEUI_STATE_CHANGED,
    PHASEUI_ACTIVE_PHASE_MODIFIED,
    RASTERIZER_OVERLOADED,
    SELECTED_OBJECT_CHANGED,
    SHOW_TOAST_MESSAGE,
    SHOW_KEYBOARD_REQUEST,
    STROKE_CONFIG_CHANGED,
    BRUSH_CHANGED
}
