package com.dodles.gdx.dodleengine.events;

/**
 * Defines the available types of events.
 */
public enum EventType {
    // Topic = "DEFAULT"
    UPDATE_PLAY_TIME,
    USER_LOGGED_OUT("USER_LOGGED_OUT"),
    USER_LOGGED_IN("USER_LOGGED_IN"),
    ANIMATION_COMPLETE,
    CALLBACK_IMPORT_DODLE("CALLBACK_IMPORT_DODLE"),
    CALLBACK_IMPORT_FILE("CALLBACK_IMPORT_FILE"),
    RECEIVE_FILE_REQUEST("RECEIVE_FILE_REQUEST"),
    COMMAND_STACK_CHANGED("COMMAND_STACK_CHANGED"),
    ENGINE_INITIALIZED("ENGINE_INITIALIZED"),
    HOST_ENGINE_SAVE_STATE("HOST_ENGINE_SAVE_STATE"),
    HOST_ENGINE_SHARE("HOST_ENGINE_SHARE"),
    HOST_ENGINE_TRASH_STATE("HOST_ENGINE_TRASH_STATE"),
    HOST_SHOW_PROFILE("HOST_SHOW_PROFILE"),
    HOST_SHOW_CHAT("HOST_SHOW_CHAT"),
    HOST_SHOW_FEED("HOST_SHOW_FEED"),
    INTERNAL_LOAD_START("INTERNAL_LOAD_START"),
    INTERNAL_LOAD_SUCCESS("INTERNAL_LOAD_SUCCESS"),
    DODLE_SAVE_SUCCESS,
    DODLE_LOAD_SUCCESS,
    DODLE_LOAD_FAILURE,
    DODLE_CREATE_NEW,
    DODLE_ENGINE_STATE_RESET,
    OK_CANCEL_STACK_CHANGED("OK_CANCEL_STACK_CHANGED"),
    TOGGLE_SLIDE_OUT("TOGGLE_SLIDE_OUT"),
    MAKE_TOAST("MAKE_TOAST"),
    UPDATE_BEARER_TOKEN("UPDATE_BEARER_TOKEN"),
    STATE_GO("STATE_GO"),
    KICK_OFF_IMPORT("KICK_OFF_IMPORT"),
    LAUNCH_EDITOR("LAUNCH_EDITOR"),
    SHARE_VIA_TWITTER("SHARE_VIA_TWITTER"),
    SHARE_VIA_INSTAGRAM("SHARE_VIA_INSTAGRAM"),
    SHARE_VIA_SMS("SHARE_VIA_SMS"),
    SHARE_VIA_EMAIL("SHARE_VIA_EMAIL"),
    HOST_ENGINE_SHOW_IMPORT_DODLE_MODAL("HOST_ENGINE_SHOW_IMPORT_DODLE_MODAL"),
    UNDO_REDO_CHANGED("UNDO_REDO_CHANGED"),
    TOOL_CHANGED("TOOL_CHANGED"),
    ANIMATION_TOOL_STATE_CHANGED,
    SELECTED_OBJECT_CHANGED,
    SCENE_ANIMATIONS_CHANGED,
    TIMELINE_INFO_UPDATED,
    ANIM_SELECTED_BLOCK_CHANGED,
    // Topic = "EDITOR"
    OK_CANCEL_STACK_POP_OK("OK_CANCEL_STACK_POP_OK"),
    OK_CANCEL_STACK_POP_CANCEL("OK_CANCEL_STACK_POP_CANCEL"),
    CHANGE_TOOL("CHANGE_TOOL"),
    CHANGE_BRUSH("CHANGE_BRUSH"),
    CHANGE_BRUSH_COLOR("CHANGE_BRUSH_COLOR"),
    CHANGE_BRUSH_RULER_MODE("CHANGE_BRUSH_RULER_MODE"),
    CHANGE_BRUSH_SIZE("CHANGE_BRUSH_SIZE"),
    CHANGE_BRUSH_OPACITY("CHANGE_BRUSH_OPACITY"),
    CHANGE_SHAPE("CHANGE_SHAPE"),
    CHANGE_SHAPE_COLOR("CHANGE_SHAPE_COLOR"),
    CHANGE_SHAPE_OPACITY("CHANGE_SHAPE_OPACITY"),
    CHANGE_SHAPE_SIZE("CHANGE_SHAPE_SIZE"),
    CHANGE_SHAPE_CORNER("CHANGE_SHAPE_CORNER"),
    CHANGE_SHAPE_ROUNDING("CHANGE_SHAPE_ROUNDING"),
    CHANGE_SHAPE_STAR_DEPTH("CHANGE_SHAPE_STAR_DEPTH"),
    ENTER_CUSTOM_SHAPE_MODE("ENTER_CUSTOM_SHAPE_MODE"),
    SHAPE_ACTIVATED("SHAPE_ACTIVATED"),
    SHAPE_DEACTIVATED("SHAPE_DEACTIVATED"),
    REGENERATE_SHAPE("REGENERATE_SHAPE"),
    UNDO("UNDO"),
    REDO("REDO"),
    DELETE_DODLE("DELETE_DODLE"),
    MOVE_CONFIG_UPDATE("MOVE_CONFIG_UPDATE"),
    ROTATE_CONFIG_UPDATE("ROTATE_CONFIG_UPDATE"),
    LAYER_OPACITY("LAYER_OPACITY"),
    LAYER_GROUP("LAYER_GROUP"),
    LAYER_UNGROUP("LAYER_UNGROUP"),
    LAYER_FLIP_HORIZONTAL("LAYER_FLIP_HORIZONTAL"),
    LAYER_FLIP_VERTICAL("LAYER_FLIP_VERTICAL"),
    LAYER_SIZE("LAYER_SIZE"),
    LAYER_FORWARD("LAYER_FORWARD"),
    LAYER_FRONT("LAYER_FRONT"),
    LAYER_BACKWARD("LAYER_BACKWARD"),
    LAYER_BACK("LAYER_BACK"),
    LAYER_COPY("LAYER_COPY"),
    LAYER_DELETE("LAYER_DELETE"),
    SET_ANIMATION_TOOL_STATE,
    ANIMATION_START,
    ANIMATION_STOP,
    ANIM_CHANGE_SELECTED_BLOCK,
    ANIM_PLAYHEAD_POSITION_CHANGED,
    ANIM_TOGGLE_PIVOT_POINT_MODE,
    SELECTED_ACTOR_EFFECTS_BUTTON_PRESSED,
    SAVE_DODLE,
    LOAD_DODLE,
    // Testing (Topic = "DEFAULT")
    PRINT_JSON("PRINT_JSON");


    private final String eventTypeDescription;

    EventType() {
        this.eventTypeDescription = "";
    }

    EventType(String eventTypeDescription) {
        this.eventTypeDescription = eventTypeDescription;
    }

    /**
     * Get the name of the event type as a string.
     */
    @Override
    public String toString() {
        return (eventTypeDescription == null || eventTypeDescription.isEmpty()) ? super.toString(): eventTypeDescription;
    }
}
