package com.dodles.gdx.dodleengine.editor.full;

import com.dodles.gdx.dodleengine.scenegraph.BaseDodlesViewGroup;

/**
 * Describes a frame in the editor drill stack.
 */
public class FullEditorStateFrame {
    private final String editorState;
    private final BaseDodlesViewGroup activeLayer;
    
    public FullEditorStateFrame(String editorState, BaseDodlesViewGroup activeLayer) {
        this.editorState = editorState;
        this.activeLayer = activeLayer;
    }
    
    /**
     * Returns the state of the editor.
     */
    public final String getEditorState() {
        return editorState;
    }
    
    /**
     * Returns the active layer.
     */
    public final BaseDodlesViewGroup getActiveLayer() {
        return activeLayer;
    }
    
    @Override
    public final boolean equals(Object other) {
        if (!(other instanceof FullEditorStateFrame)) {
            return false;
        }
        
        FullEditorStateFrame femOther = (FullEditorStateFrame) other;
        
        return this.editorState == femOther.editorState && this.activeLayer == femOther.activeLayer;
    }

    @Override
    public final int hashCode() {
        // This was autogenerated by NetBeans, I have no idea what it's doing. :)
        int hash = 7;
        // CHECKSTYLE.OFF: AvoidInlineConditionals - generated code
        hash = 47 * hash + (this.editorState != null ? this.editorState.hashCode() : 0);
        hash = 47 * hash + (this.activeLayer != null ? this.activeLayer.getName().hashCode() : 0);
        // CHECKSTYLE.ON: AvoidInlineConditionals
        return hash;
    }
}
