// This file is auto-generated by the gradle build, alter dodles.properties to change it's values, and don't check in to source control!

package com.dodles.mobileinterop;

/**
 * Application configuration parameters.
 */
public final class ApplicationConfig {
    private static String webURL = "https://website.dev.dodl.es";
    private static String topNavURL = "https://website.dev.dodl.es/topnav.html";
    private static String leftNavURL = "https://website.dev.dodl.es/leftnav.html";
    private static String socialURL = "https://website.dev.dodl.es/social.html";

    private ApplicationConfig() {
    }

    /**
     * Returns the URL of the dodles web site.
     */
    public static String getWebURL() {
        return webURL;
    }

    /**
     * Returns the top navigation URL of the dodles web site.
     */
    public static String getTopNavURL() {
        return topNavURL;
    }

    /**
     * Returns the top navigation URL of the dodles web site.
     */
    public static String getLeftNavURL() {
        return leftNavURL;
    }

    /**
     * Returns the top navigation URL of the dodles web site.
     */
    public static String getSocialURL() {
        return socialURL;
    }
}
